routes/web.php
<?php
    /*
    |--------------------------------------------------------------------------
    | Web Routes
    |--------------------------------------------------------------------------
    |
    | Here is where you can register web routes for your application. These
    | routes are loaded by the RouteServiceProvider within a group which
    | contains the "web" middleware group. Now create something great!
    |
    */

    Auth::routes();

    Route::get('/', 'HomeController@index')->name('home');

    Route::prefix('system')->namespace('System')->group(function(){
        Route::middleware('admin')->resource('users','UsersController');
    });

    Route::prefix('local')->namespace('Local')->group(function(){
        Route::middleware('admin')->resource('units','UnitsController');

        Route::middleware('admin')->get('employees/sync','EmployeeSyncController@edit')->name('employees.sync');
        Route::middleware('admin')->post('employees/sync','EmployeeSyncController@update')->name('employees.sync');
        Route::middleware('admin')->resource('employees','EmployeesController');

        Route::get('employees/find/{ein}', 'EmployeesController@show');

    });

app/Models/Employee.php
<?php namespace App\Models;
    use App\Base\Model;

    class Employee extends Model
    {
          /**
           * The attributes that are mass assignable.
           *
           * @var array
           */
          protected $fillable = [
              'first_name',
              'last_name',
              'middle_initial',
              'address_line_one',
              'address_line_two',
              'city',
              'state',
              'zip',
              'phone_number',
              'finance_number',
              'ein',
              'level',
              'step',
              'off_days',
              'duty_hours',
              'preference_eligible',
              'craft',
              'status',
              'is_member',
              'seniority_date'
          ];

          /**
           * The attributes that are encrypted.
           *
           * @var array
           */
          protected $encrypts = [
            'first_name',
            'middle_initial',
            'last_name',
            'address_line_one',
            'address_line_two',
            'city',
            'state',
            'zip',
            'phone_number',
            'off_days',
            'duty_hours'
          ];

          protected $dates = [
            'seniority_date'
          ];
    }

app/Http/Controllers/Local/EmployeeSyncController.php
<?php namespace App\Http\Controllers\Local;
    use Illuminate\Http\Request;
    use App\Http\Controllers\Controller;
    use App\Imports\MembersImport;
    use App\Imports\NonMembersImport;
    use App\Models\Employee;

    class EmployeeSyncController extends Controller
    {
        /**
         * Show the form for editing the specified resource.
         *
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function edit()
        {
            return view('local.employees.sync');
        }

        /**
         * Update the specified resource in storage.
         *
         * @param  \Illuminate\Http\Request  $request
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function update(Request $request)
        {
            Employee::truncate();

            \Excel::import(new MembersImport, $request->file('m_list'));
            \Excel::import(new NonMembersImport, $request->file('nm_list'));

            return redirect()->route('employees.index')
              ->withStatus('The employee data has been successfully synced!');
        }
    }

app/Http/Controllers/Local/EmployeesController.php
<?php namespace App\Http\Controllers\Local;
    use Illuminate\Http\Request;
    use App\Http\Controllers\Controller;
    use App\Models\Employee;
    use Carbon\Carbon;


    class EmployeesController extends Controller
    {
        /**
         * Display a listing of the resource.
         *
         * @return \Illuminate\Http\Response
         */
        public function index()
        {
            $collection = Employee::paginate(25);

            return view('local.employees.index')
              ->withEmployees($collection);
        }

        /**
         * Show the form for creating a new resource.
         *
         * @return \Illuminate\Http\Response
         */
        public function create()
        {
            return view('local.employees.create');
        }

        /**
         * Store a newly created resource in storage.
         *
         * @param  \Illuminate\Http\Request  $request
         * @return \Illuminate\Http\Response
         */
        public function store(Request $request)
        {
              $request->validate([
                  'first_name'            => ['required'],
                  'last_name'             => ['required'],
                  'address_line_one'      => ['required'],
                  'city'                  => ['required'],
                  'state'                 => ['required'],
                  'zip'                   => ['required'],
                  'finance_number'        => ['required'],
                  'ein'                   => ['required'],
              ]);

              Employee::create([
                'first_name'              => $request->first_name,
                'middle_initial'          => $request->middle_initial,
                'last_name'               => $request->last_name,
                'ein'                     => $request->ein,
                'finance_number'          => $request->finance_number,
                'craft'                   => $request->craft,
                'status'                  => $request->status,
                'level'                   => $request->level,
                'step'                    => $request->step,
                'address_line_one'        => $request->address_line_one,
                'address_line_two'        => $request->address_line_two,
                'city'                    => $request->city,
                'state'                   => $request->state,
                'zip'                     => $request->zip,
                'level'                   => $request->level,
                'finance_number'          => $request->finance_number,
                'phone_number'            => $request->phone_number,
                'duty_hours'              => $request->duty_hours,
                'off_days'                => $request->duty_hours,
                'seniority_date'          => Carbon::parse($request->seniority_date),
                'preference_eligible'     => $request->has('preference_eligible'),
                'is_member'               => $request->has('is_member')
              ]);

              return redirect()->route('employees.index')
                ->withStatus("The employee was created successfully!");
        }

        /**
         * Display the specified resource.
         *
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function show($ein)
        {
            $employee = Employee::where('ein',$ein)
              ->first();

            if(is_null($employee)){
                abort(404, "No employee was found");
            }

            return [
              'first_name'          => $employee->first_name,
              'middle_initial'      => $employee->middle_initial,
              'last_name'           => $employee->last_name,
              'finance_number'      => $employee->finance_number,
              'status'              => $employee->status
            ];
        }

        /**
         * Show the form for editing the specified resource.
         *
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function edit(Employee $employee)
        {
            return view('local.employees.edit')
              ->withEmployee($employee);
        }

        /**
         * Update the specified resource in storage.
         *
         * @param  \Illuminate\Http\Request  $request
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function update(Request $request, Employee $employee)
        {
            $request->validate([
                'first_name'            => ['required'],
                'last_name'             => ['required'],
                'address_line_one'      => ['required'],
                'city'                  => ['required'],
                'state'                 => ['required'],
                'zip'                   => ['required'],
                'finance_number'        => ['required'],
                'ein'                   => ['required']
            ]);

            $employee->update([
              'first_name'              => $request->first_name,
              'middle_initial'          => $request->middle_initial,
              'last_name'               => $request->last_name,
              'ein'                     => $request->ein,
              'finance_number'          => $request->finance_number,
              'craft'                   => $request->craft,
              'status'                  => $request->status,
              'level'                   => $request->level,
              'step'                    => $request->step,
              'address_line_one'        => $request->address_line_one,
              'address_line_two'        => $request->address_line_two,
              'city'                    => $request->city,
              'state'                   => $request->state,
              'zip'                     => $request->zip,
              'level'                   => $request->level,
              'finance_number'          => $request->finance_number,
              'phone_number'            => $request->phone_number,
              'duty_hours'              => $request->duty_hours,
              'off_days'                => $request->duty_hours,
              'seniority_date'          => Carbon::parse($request->seniority_date),
              'preference_eligible'     => $request->has('preference_eligible'),
              'is_member'               => $request->has('is_member')
            ]);

            return redirect()->route('employees.index')
              ->withStatus('The employee was updated successfully!');
        }

        /**
         * Remove the specified resource from storage.
         *
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function destroy(Employee $employee)
        {
            $employee->delete();

            return redirect()->route('employees.index')
              ->withStatus('The employee has been deleted successfully!');
        }
    }

app/Http/Controllers/Local/UnitsController.php
<?php namespace App\Http\Controllers\Local;
    use Illuminate\Http\Request;
    use App\Http\Controllers\Controller;
    use App\Models\Unit;


    class UnitsController extends Controller
    {
        /**
         * Display a listing of the resource.
         *
         * @return \Illuminate\Http\Response
         */
        public function index()
        {
            $collection = Unit::paginate(25);

            return view('local.units.index')
              ->withUnits($collection);
        }

        /**
         * Show the form for creating a new resource.
         *
         * @return \Illuminate\Http\Response
         */
        public function create()
        {
            return view('local.units.create');
        }

        /**
         * Store a newly created resource in storage.
         *
         * @param  \Illuminate\Http\Request  $request
         * @return \Illuminate\Http\Response
         */
        public function store(Request $request)
        {
              $request->validate([
                  'name'                  => ['required'],
                  'address_line_one'      => ['required'],
                  'city'                  => ['required'],
                  'state'                 => ['required'],
                  'zip'                   => ['required'],
                  'finance_number'        => ['required']
              ]);

              Unit::create([
                'name'                    => $request->name,
                'address_line_one'        => $request->address_line_one,
                'address_line_two'        => $request->address_line_two,
                'city'                    => $request->city,
                'state'                   => $request->state,
                'zip'                     => $request->zip,
                'level'                   => $request->level,
                'finance_number'          => $request->finance_number,
                'phone_number'            => $request->phone_number,
                'fax_number'              => $request->fax_number
              ]);

              return redirect()->route('units.index')
                ->withStatus("The unit was created successfully!");
        }

        /**
         * Display the specified resource.
         *
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function show($id)
        {
            //
        }

        /**
         * Show the form for editing the specified resource.
         *
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function edit(Unit $unit)
        {
            return view('local.units.edit')
              ->withUnit($unit);
        }

        /**
         * Update the specified resource in storage.
         *
         * @param  \Illuminate\Http\Request  $request
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function update(Request $request, Unit $unit)
        {
            $request->validate([
                'name'                  => ['required'],
                'address_line_one'      => ['required'],
                'city'                  => ['required'],
                'state'                 => ['required'],
                'zip'                   => ['required'],
                'finance_number'        => ['required']
            ]);

            $unit->update([
              'name'                    => $request->name,
              'address_line_one'        => $request->address_line_one,
              'address_line_two'        => $request->address_line_two,
              'city'                    => $request->city,
              'state'                   => $request->state,
              'zip'                     => $request->zip,
              'level'                   => $request->level,
              'finance_number'          => $request->finance_number,
              'phone_number'            => $request->phone_number,
              'fax_number'              => $request->fax_number
            ]);

            return redirect()->route('units.index')
              ->withStatus('The unit was updated successfully!');
        }

        /**
         * Remove the specified resource from storage.
         *
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function destroy(Unit $unit)
        {
            $unit->delete();

            return redirect()->route('units.index')
              ->withStatus('The unit has been deleted successfully!');
        }
    }

resources/views/local/employees/index.blade.php
@extends('layouts.app')
    @section('content')
        <div class="container">
            <div class="row justify-content-center">
              <div class="col-md-3">
                  <div class="card">
                      <div class="card-header">Essential Links</div>

                      <div class="card-body">
                          <a href="{{ route('employees.create') }}" class="btn btn-secondary mb-1">Create New Employee</a>
                          @if(Auth::user()->type === 12 OR Auth::user()->type === 14)<a href="{{ route('employees.sync') }}" class="btn btn-secondary">Sync Employee Data</a>@endif
                      </div>
                  </div>
              </div>
                <div class="col-md-9">
                    <div class="card">
                        <div class="card-header">View Employee List</div>

                        <div class="card-body">
                            @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            @endif

                            <div class="table-responsive">
                               <table class="table table-bordered">
                                  <tr>
                                    <th>Name</th>
                                    <th>EIN</th>
                                    <th>Work Finance Number</th>
                                    <th>Actions</th>
                                  </tr>

                                  @foreach($employees as $employee)
                                    <tr>
                                      <td>{{ $employee->first_name }} {{ $employee->last_name }}</td>
                                      <td>{{ $employee->ein }}</td>
                                      <td>{{ $employee->finance_number }}</td>
                                      <td>
                                        <a href="{{ route('employees.edit', $employee) }}" class="btn btn-secondary">Edit</a>

                                        <a class="btn btn-danger" href="{{ route('employees.destroy', $employee) }}"
                                           onclick="event.preventDefault();
                                                         document.getElementById('delete-{{ $employee->id }}').submit();">Delete</a>
                                        <form id="delete-{{ $employee->id }}" action="{{ route('employees.destroy', $employee) }}" method="POST">
                                          @method('DELETE')
                                          @csrf
                                        </form>
                                      </td>
                                    </tr>
                                  @endforeach

                               </table>
                            </div>

                            {{ $employees->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endsection

resources/views/local/employees/sync.blade.php
@extends('layouts.app')
    @section('content')
        <div class="container">
            <div class="row justify-content-center">
              <div class="col-md-3">
                  <div class="card">
                      <div class="card-header">Essential Links</div>

                      <div class="card-body">
                          <a href="{{ route('employees.create') }}" class="btn btn-secondary mb-1">Create New Employee</a>
                          @if(Auth::user()->type === 12 OR Auth::user()->type === 14)<a href="{{ route('employees.sync') }}" class="btn btn-secondary">Sync Employee Data</a>@endif
                      </div>
                  </div>
              </div>
                <div class="col-md-9">
                    <div class="card">
                        <div class="card-header">Sync Employee Data</div>

                        <div class="card-body">
                            <p class="help-block">This feature allows authorized officers to sync the employee list using the APWU Member/Non-Member and DCO Reports provided by National. Please ensure you upload only the latest copy of each report, or you may cause inaccurate information to be synced to the MyMHAL Application.</p>
                            @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            @endif

                            <form method="POST" action="{{ route('employees.sync') }}" enctype="multipart/form-data">
                                @csrf

                                <div class="form-group row">
                                    <label for="m_list" class="col-md-4 col-form-label text-md-right">{{ __('Member List') }}</label>

                                    <div class="col-md-6">
                                        <input id="m_list" type="file" class="form-control-file{{ $errors->has('m_list') ? ' is-invalid' : '' }}" name="m_list" required autofocus>

                                        @if ($errors->has('m_list'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('m_list') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="nm_list" class="col-md-4 col-form-label text-md-right">{{ __('Non-Member List') }}</label>

                                    <div class="col-md-6">
                                        <input id="nm_list" type="file" class="form-control-file{{ $errors->has('middle_initial') ? ' is-invalid' : '' }}" name="nm_list" required autofocus>

                                        @if ($errors->has('nm_list'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('nm_list') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="dco_list" class="col-md-4 col-form-label text-md-right">{{ __('Dues Check Off') }}</label>

                                    <div class="col-md-6">
                                        <input id="dco_list" type="file" class="form-control-file{{ $errors->has('dco_list') ? ' is-invalid' : '' }}" name="dco_list" required autofocus>

                                        @if ($errors->has('dco_list'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('dco_list') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group row mb-0">
                                    <div class="col-md-6 offset-md-4">
                                        <button type="submit" class="btn btn-primary">
                                            {{ __('Save') }}
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endsection

    @section('vue')
        <script type="text/javascript">
            new Vue({
                el: "#app",

                data: {
                  steps: ["FF","EE","DD","CC","BB","AA","A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P"],

                  level: "6"
                },

                methods: {
                  onChange: function(event) {
                    console.log(event.target.value);

                    switch(event.target.value){
                      case "3":
                      case "4":
                        this.steps = ["JJ","II","HH","GG","FF","EE","DD","CC","BB","AA","A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P"];
                        break;
                      case "5":
                      case "6":
                      case "7":
                      case "8":
                          this.steps = ["FF","EE","DD","CC","BB","AA","A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P"];
                          break;
                      case "9":
                      case "10":
                      case "11":
                          this.steps = ["D","E","F","G","H","I","J","K","L","M","N","O","P"];
                          break;
                    }
                  }
                }
            });
        </script>
    @endsection