routes/web.php
<?php
    /*
    |--------------------------------------------------------------------------
    | Web Routes
    |--------------------------------------------------------------------------
    |
    | Here is where you can register web routes for your application. These
    | routes are loaded by the RouteServiceProvider within a group which
    | contains the "web" middleware group. Now create something great!
    |
    */

    Auth::routes();

    Route::get('/', 'HomeController@index')->name('home');

    Route::prefix('system')->namespace('System')->group(function(){
        Route::middleware('admin')->resource('users','UsersController');
    });

    Route::prefix('local')->namespace('Local')->group(function(){
        Route::middleware('admin')->resource('units','UnitsController');

        Route::middleware('admin')->get('employees/sync','EmployeeSyncController@edit')->name('employees.sync');
        Route::middleware('admin')->post('employees/sync','EmployeeSyncController@update')->name('employees.sync');
        Route::middleware('admin')->resource('employees','EmployeesController');

        Route::get('employees/find/{ein}', 'EmployeesController@show');

    });

app/Models/Unit.php
<?php namespace App\Models;
    use App\Base\Model;

    class Unit extends Model
    {
        /**
         * The attributes that are mass assignable.
         *
         * @var array
         */
        protected $fillable = [
            'name',
            'address_line_one',
            'address_line_two',
            'city',
            'state',
            'zip',
            'phone_number',
            'fax_number',
            'finance_number',
            'level'
        ];

        /**
         * The attributes that are encrypted.
         *
         * @var array
         */
        protected $encrypts = [
          'name',
          'address_line_one',
          'address_line_two',
          'city',
          'state',
          'zip',
          'phone_number',
          'fax_number'
        ];
    }

app/Http/Controllers/Local/EmployeeSyncController.php
<?php namespace App\Http\Controllers\Local;
    use Illuminate\Http\Request;
    use App\Http\Controllers\Controller;
    use App\Imports\MembersImport;
    use App\Imports\NonMembersImport;
    use App\Models\Employee;

    class EmployeeSyncController extends Controller
    {
        /**
         * Show the form for editing the specified resource.
         *
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function edit()
        {
            return view('local.employees.sync');
        }

        /**
         * Update the specified resource in storage.
         *
         * @param  \Illuminate\Http\Request  $request
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function update(Request $request)
        {
            Employee::truncate();

            \Excel::import(new MembersImport, $request->file('m_list'));
            \Excel::import(new NonMembersImport, $request->file('nm_list'));

            return redirect()->route('employees.index')
              ->withStatus('The employee data has been successfully synced!');
        }
    }

app/Http/Controllers/Local/EmployeesController.php
<?php namespace App\Http\Controllers\Local;
    use Illuminate\Http\Request;
    use App\Http\Controllers\Controller;
    use App\Models\Employee;
    use Carbon\Carbon;


    class EmployeesController extends Controller
    {
        /**
         * Display a listing of the resource.
         *
         * @return \Illuminate\Http\Response
         */
        public function index()
        {
            $collection = Employee::paginate(25);

            return view('local.employees.index')
              ->withEmployees($collection);
        }

        /**
         * Show the form for creating a new resource.
         *
         * @return \Illuminate\Http\Response
         */
        public function create()
        {
            return view('local.employees.create');
        }

        /**
         * Store a newly created resource in storage.
         *
         * @param  \Illuminate\Http\Request  $request
         * @return \Illuminate\Http\Response
         */
        public function store(Request $request)
        {
              $request->validate([
                  'first_name'            => ['required'],
                  'last_name'             => ['required'],
                  'address_line_one'      => ['required'],
                  'city'                  => ['required'],
                  'state'                 => ['required'],
                  'zip'                   => ['required'],
                  'finance_number'        => ['required'],
                  'ein'                   => ['required'],
              ]);

              Employee::create([
                'first_name'              => $request->first_name,
                'middle_initial'          => $request->middle_initial,
                'last_name'               => $request->last_name,
                'ein'                     => $request->ein,
                'finance_number'          => $request->finance_number,
                'craft'                   => $request->craft,
                'status'                  => $request->status,
                'level'                   => $request->level,
                'step'                    => $request->step,
                'address_line_one'        => $request->address_line_one,
                'address_line_two'        => $request->address_line_two,
                'city'                    => $request->city,
                'state'                   => $request->state,
                'zip'                     => $request->zip,
                'level'                   => $request->level,
                'finance_number'          => $request->finance_number,
                'phone_number'            => $request->phone_number,
                'duty_hours'              => $request->duty_hours,
                'off_days'                => $request->duty_hours,
                'seniority_date'          => Carbon::parse($request->seniority_date),
                'preference_eligible'     => $request->has('preference_eligible'),
                'is_member'               => $request->has('is_member')
              ]);

              return redirect()->route('employees.index')
                ->withStatus("The employee was created successfully!");
        }

        /**
         * Display the specified resource.
         *
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function show($ein)
        {
            $employee = Employee::where('ein',$ein)
              ->first();

            if(is_null($employee)){
                abort(404, "No employee was found");
            }

            return [
              'first_name'          => $employee->first_name,
              'middle_initial'      => $employee->middle_initial,
              'last_name'           => $employee->last_name,
              'finance_number'      => $employee->finance_number,
              'status'              => $employee->status
            ];
        }

        /**
         * Show the form for editing the specified resource.
         *
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function edit(Employee $employee)
        {
            return view('local.employees.edit')
              ->withEmployee($employee);
        }

        /**
         * Update the specified resource in storage.
         *
         * @param  \Illuminate\Http\Request  $request
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function update(Request $request, Employee $employee)
        {
            $request->validate([
                'first_name'            => ['required'],
                'last_name'             => ['required'],
                'address_line_one'      => ['required'],
                'city'                  => ['required'],
                'state'                 => ['required'],
                'zip'                   => ['required'],
                'finance_number'        => ['required'],
                'ein'                   => ['required']
            ]);

            $employee->update([
              'first_name'              => $request->first_name,
              'middle_initial'          => $request->middle_initial,
              'last_name'               => $request->last_name,
              'ein'                     => $request->ein,
              'finance_number'          => $request->finance_number,
              'craft'                   => $request->craft,
              'status'                  => $request->status,
              'level'                   => $request->level,
              'step'                    => $request->step,
              'address_line_one'        => $request->address_line_one,
              'address_line_two'        => $request->address_line_two,
              'city'                    => $request->city,
              'state'                   => $request->state,
              'zip'                     => $request->zip,
              'level'                   => $request->level,
              'finance_number'          => $request->finance_number,
              'phone_number'            => $request->phone_number,
              'duty_hours'              => $request->duty_hours,
              'off_days'                => $request->duty_hours,
              'seniority_date'          => Carbon::parse($request->seniority_date),
              'preference_eligible'     => $request->has('preference_eligible'),
              'is_member'               => $request->has('is_member')
            ]);

            return redirect()->route('employees.index')
              ->withStatus('The employee was updated successfully!');
        }

        /**
         * Remove the specified resource from storage.
         *
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function destroy(Employee $employee)
        {
            $employee->delete();

            return redirect()->route('employees.index')
              ->withStatus('The employee has been deleted successfully!');
        }
    }

app/Http/Controllers/Local/UnitsController.php
<?php namespace App\Http\Controllers\Local;
    use Illuminate\Http\Request;
    use App\Http\Controllers\Controller;
    use App\Models\Unit;


    class UnitsController extends Controller
    {
        /**
         * Display a listing of the resource.
         *
         * @return \Illuminate\Http\Response
         */
        public function index()
        {
            $collection = Unit::paginate(25);

            return view('local.units.index')
              ->withUnits($collection);
        }

        /**
         * Show the form for creating a new resource.
         *
         * @return \Illuminate\Http\Response
         */
        public function create()
        {
            return view('local.units.create');
        }

        /**
         * Store a newly created resource in storage.
         *
         * @param  \Illuminate\Http\Request  $request
         * @return \Illuminate\Http\Response
         */
        public function store(Request $request)
        {
              $request->validate([
                  'name'                  => ['required'],
                  'address_line_one'      => ['required'],
                  'city'                  => ['required'],
                  'state'                 => ['required'],
                  'zip'                   => ['required'],
                  'finance_number'        => ['required']
              ]);

              Unit::create([
                'name'                    => $request->name,
                'address_line_one'        => $request->address_line_one,
                'address_line_two'        => $request->address_line_two,
                'city'                    => $request->city,
                'state'                   => $request->state,
                'zip'                     => $request->zip,
                'level'                   => $request->level,
                'finance_number'          => $request->finance_number,
                'phone_number'            => $request->phone_number,
                'fax_number'              => $request->fax_number
              ]);

              return redirect()->route('units.index')
                ->withStatus("The unit was created successfully!");
        }

        /**
         * Display the specified resource.
         *
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function show($id)
        {
            //
        }

        /**
         * Show the form for editing the specified resource.
         *
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function edit(Unit $unit)
        {
            return view('local.units.edit')
              ->withUnit($unit);
        }

        /**
         * Update the specified resource in storage.
         *
         * @param  \Illuminate\Http\Request  $request
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function update(Request $request, Unit $unit)
        {
            $request->validate([
                'name'                  => ['required'],
                'address_line_one'      => ['required'],
                'city'                  => ['required'],
                'state'                 => ['required'],
                'zip'                   => ['required'],
                'finance_number'        => ['required']
            ]);

            $unit->update([
              'name'                    => $request->name,
              'address_line_one'        => $request->address_line_one,
              'address_line_two'        => $request->address_line_two,
              'city'                    => $request->city,
              'state'                   => $request->state,
              'zip'                     => $request->zip,
              'level'                   => $request->level,
              'finance_number'          => $request->finance_number,
              'phone_number'            => $request->phone_number,
              'fax_number'              => $request->fax_number
            ]);

            return redirect()->route('units.index')
              ->withStatus('The unit was updated successfully!');
        }

        /**
         * Remove the specified resource from storage.
         *
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function destroy(Unit $unit)
        {
            $unit->delete();

            return redirect()->route('units.index')
              ->withStatus('The unit has been deleted successfully!');
        }
    }

resources/views/local/units/create.blade.php
@extends('layouts.app')
    @section('content')
        <div class="container">
            <div class="row justify-content-center">
              <div class="col-md-3">
                  <div class="card">
                      <div class="card-header">Essential Links</div>

                      <div class="card-body">
                          <a href="{{ route('units.create') }}" class="btn btn-secondary">Create New Unit</a>
                      </div>
                  </div>
              </div>
                <div class="col-md-9">
                    <div class="card">
                        <div class="card-header">Create New Unit</div>

                        <div class="card-body">
                            @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            @endif

                            <form method="POST" action="{{ route('units.store') }}">
                                @csrf

                                <div class="form-group row">
                                    <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                    <div class="col-md-6">
                                        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required autofocus>

                                        @if ($errors->has('name'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('name') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="level" class="col-md-4 col-form-label text-md-right">{{ __('Level') }}</label>

                                    <div class="col-md-6">
                                        <input id="level" type="text" class="form-control{{ $errors->has('level') ? ' is-invalid' : '' }}" name="level" value="{{ old('level') }}" required autofocus>

                                        @if ($errors->has('ein'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('ein') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="finance_number" class="col-md-4 col-form-label text-md-right">{{ __('Finance Number') }}</label>

                                    <div class="col-md-6">
                                        <input id="finance_number" type="text" class="form-control{{ $errors->has('finance_number') ? ' is-invalid' : '' }}" name="finance_number" value="{{ old('finance_number') }}" required autofocus>

                                        @if ($errors->has('finance_number'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('finance_number') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <hr />

                                <div class="form-group row">
                                    <label for="address_line_one" class="col-md-4 col-form-label text-md-right">{{ __('Address Line One') }}</label>

                                    <div class="col-md-6">
                                        <input id="address_line_one" type="text" class="form-control{{ $errors->has('address_line_one') ? ' is-invalid' : '' }}" name="address_line_one" value="{{ old('address_line_one') }}" required autofocus>

                                        @if ($errors->has('address_line_one'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('address_line_one') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="address_line_two" class="col-md-4 col-form-label text-md-right">{{ __('Address Line Two') }}</label>

                                    <div class="col-md-6">
                                        <input id="address_line_two" type="text" class="form-control{{ $errors->has('address_line_two') ? ' is-invalid' : '' }}" name="address_line_two" value="{{ old('address_line_two') }}" autofocus>

                                        @if ($errors->has('address_line_two'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('address_line_two') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('City') }}</label>

                                    <div class="col-md-6">
                                        <input id="city" type="text" class="form-control{{ $errors->has('city') ? ' is-invalid' : '' }}" name="city" value="{{ old('city') }}" required autofocus>

                                        @if ($errors->has('city'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('city') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('State') }}</label>

                                    <div class="col-md-6">
                                        <select class="form-control {{ $errors->has('state') ? ' is-invalid' : ''}}" name="state" selected="NY">
                                          @foreach(CountryState::getStates('US') as $abbr => $state)
                                            <option value="{{ $abbr }}" @if(old('state', 'NY') === $abbr) selected @endif>{{ $state }}</option>
                                          @endforeach

                                        </select>

                                        @if ($errors->has('state'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('state') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('ZIP') }}</label>

                                    <div class="col-md-6">
                                        <input id="zip" type="text" class="form-control{{ $errors->has('zip') ? ' is-invalid' : '' }}" name="zip" value="{{ old('zip') }}" required autofocus>

                                        @if ($errors->has('zip'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('zip') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <hr />

                                <div class="form-group row">
                                    <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Phone Number') }}</label>

                                    <div class="col-md-6">
                                        <input id="phone_number" type="text" class="form-control{{ $errors->has('phone_number') ? ' is-invalid' : '' }}" name="phone_number" value="{{ old('phone_number') }}" autofocus>

                                        @if ($errors->has('phone_number'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('phone_number') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Fax Number') }}</label>

                                    <div class="col-md-6">
                                        <input id="fax_number" type="text" class="form-control{{ $errors->has('fax_number') ? ' is-invalid' : '' }}" name="fax_number" value="{{ old('fax_number') }}" autofocus>

                                        @if ($errors->has('fax_number'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('fax_number') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group row mb-0">
                                    <div class="col-md-6 offset-md-4">
                                        <button type="submit" class="btn btn-primary">
                                            {{ __('Save') }}
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endsection

resources/views/local/units/index.blade.php
@extends('layouts.app')
    @section('content')
        <div class="container">
            <div class="row justify-content-center">
              <div class="col-md-3">
                  <div class="card">
                      <div class="card-header">Essential Links</div>

                      <div class="card-body">
                          <a href="{{ route('units.create') }}" class="btn btn-secondary">Create New Unit</a>
                      </div>
                  </div>
              </div>
                <div class="col-md-9">
                    <div class="card">
                        <div class="card-header">View Unit List</div>

                        <div class="card-body">
                            @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            @endif

                            <div class="table-responsive">
                               <table class="table table-bordered">
                                  <tr>
                                    <th>Name</th>
                                    <th>Level</th>
                                    <th>Actions</th>
                                  </tr>

                                  @foreach($units as $unit)
                                    <tr>
                                      <td>{{ $unit->name }}</td>
                                      <td>{{ $unit->level }}</td>
                                      <td>
                                        <a href="{{ route('units.edit', $unit) }}" class="btn btn-secondary">Edit</a>

                                        <a class="btn btn-danger" href="{{ route('units.destroy', $unit) }}"
                                           onclick="event.preventDefault();
                                                         document.getElementById('delete-{{ $unit->id }}').submit();">Delete</a>
                                        <form id="delete-{{ $unit->id }}" action="{{ route('units.destroy', $unit) }}" method="POST">
                                          @method('DELETE')
                                          @csrf
                                        </form>
                                      </td>
                                    </tr>
                                  @endforeach

                               </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endsection