routes/web.php
<?php
    /*
    |--------------------------------------------------------------------------
    | Web Routes
    |--------------------------------------------------------------------------
    |
    | Here is where you can register web routes for your application. These
    | routes are loaded by the RouteServiceProvider within a group which
    | contains the "web" middleware group. Now create something great!
    |
    */

    Auth::routes();

    Route::get('/', 'HomeController@index')->name('home');

    Route::prefix('system')->namespace('System')->group(function(){
        Route::middleware('admin')->resource('users','UsersController');
    });

    Route::prefix('local')->namespace('Local')->group(function(){
        Route::middleware('admin')->resource('units','UnitsController');

        Route::middleware('admin')->get('employees/sync','EmployeeSyncController@edit')->name('employees.sync');
        Route::middleware('admin')->post('employees/sync','EmployeeSyncController@update')->name('employees.sync');
        Route::middleware('admin')->resource('employees','EmployeesController');

        Route::get('employees/find/{ein}', 'EmployeesController@show');

    });

app/Models/User.php
<?php namespace App\Models;
    use Illuminate\Notifications\Notifiable;
    use Illuminate\Auth\Authenticatable;
    use Illuminate\Foundation\Auth\Access\Authorizable;
    use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
    use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
    use App\Base\Model;

    class User extends Model implements AuthenticatableContract, AuthorizableContract
    {
        use Notifiable, Authorizable, Authenticatable;

        /**
         * The attributes that are mass assignable.
         *
         * @var array
         */
        protected $fillable = [
            'ein',
            'username',
            'email',
            'password',
            'type',
            'authorized_payee',
            'authorized_signer'
        ];

        /**
         * The attributes that are encrypted.
         *
         * @var array
         */
        protected $encrypts = [
          'username',
          'email'
        ];

        /**
         * The attributes that are hashed.
         *
         * @var array
         */
        protected $hashes = [
          'username',
          'email'
        ];

        /**
         * The attributes that should be hidden for arrays.
         *
         * @var array
         */
        protected $hidden = [
            'password',
            'remember_token',
        ];

        /**
         * The attributes that appended to the nodel.
         *
         * @var array
         */
         protected $appends = [
           'type_text',
           'is_admin',
           'is_board'
         ];

         /**
          * The attributes that are casted to a different type.
          *
          * @var array
          */
          protected $casts = [
            'authorized_payee'        => 'boolean',
            'authorized_signer'       => 'boolean'
          ];

         public function getIsAdminAttribute(){
           return $this->type >= 11;
         }

         public function getIsBoardAttribute(){
           return $this->type >= 2;
         }

         public function getTypeTextAttribute(){
           switch($this->type){
              case 0:
                return "Member";
              case 1:
                return "Steward";
              case 2:
                return "Director, Research and Education";
              case 3:
                return "Director, Human Relations";
              case 4:
                return "Director, Organization";
              case 5:
                return "Segeant at Arms";
              case 6:
                return "Chief Steward";
              case 7:
                return "Director, Clerk Craft";
              case 8:
                return "Director, Maintenance Craft";
              case 9:
                return "Recording Secretary";
              case 10:
                return "Corresponding Secretary";
              case 11:
                return "Trustee";
              case 12:
                return "Treasurer";
              case 13:
                return "Vice President";
              case 14:
                return "President";

           }
         }

         public function profile(){
             return $this->hasOne(Employee::class, "ein", "ein");
         }
    }

app/Http/Controllers/System/UsersController.php
<?php namespace App\Http\Controllers\System;
    use Illuminate\Http\Request;
    use App\Http\Controllers\Controller;
    use App\Models\User;
    use Illuminate\Support\Facades\Hash;
    use App\Notifications\Accounts\AccountWasCreated;
    use Illuminate\Support\Facades\Auth;

    class UsersController extends Controller
    {
        /**
         * Display a listing of the resource.
         *
         * @return \Illuminate\Http\Response
         */
        public function index()
        {
            $collection = User::paginate(25);

            return view('system.users.index')
              ->withUsers($collection);
        }

        /**
         * Show the form for creating a new resource.
         *
         * @return \Illuminate\Http\Response
         */
        public function create()
        {
            return view('system.users.create');
        }

        /**
         * Store a newly created resource in storage.
         *
         * @param  \Illuminate\Http\Request  $request
         * @return \Illuminate\Http\Response
         */
        public function store(Request $request)
        {
            $request->validate([
              'ein'           => ['required', 'unique:users', 'min:8', 'max:8'],
              'username'      => ['required', 'min:5','max:30'],
              'email'         => ['required', 'string','email','max:255'],
            ]);

            $password = str_random(25);

            $user = User::create([
                'ein'               => $request->ein,
                'username'          => $request->username,
                'email'             => $request->email,
                'password'          => Hash::make($password),
                'type'              => $request->type,
                'authorized_payee'  => $request->has('authorized_payee'),
                'authorized_signer' => $request->has('authorized_signer')
            ]);

            $user->notify(new AccountWasCreated($password));

            return redirect()->route('users.index')
              ->withStatus("The user account was created successfully!");
        }

        /**
         * Show the form for editing the specified resource.
         *
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function edit(User $user)
        {
            return view('system.users.edit')
              ->withUser($user);
        }

        /**
         * Update the specified resource in storage.
         *
         * @param  \Illuminate\Http\Request  $request
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function update(Request $request, User $user)
        {
            $attributes = [
                'username'          => $request->username,
                'email'             => $request->email,
                'type'              => $request->type
            ];

            if(Auth::user()->type === 12){
              $attributes['authorized_payee'] = $request->has('authorized_payee');
              $attributes['authorized_signer'] = $request->has('authorized_signer');
            }
            $user->update($attributes);

            return redirect()->route('users.index')
              ->withStatus("The user account was editted successfully!");
        }

        /**
         * Remove the specified resource from storage.
         *
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function destroy(User $user)
        {
            $user->delete();

            return redirect()->route('users.index')
              ->withStatus("The user account was deleted successfully!");
        }
    }

resources/views/system/users/create.blade.php
@extends('layouts.app')
    @section('content')
        <div class="container">
            <div class="row justify-content-center">
              <div class="col-md-3">
                  <div class="card">
                      <div class="card-header">Essential Links</div>

                      <div class="card-body">
                          <a href="{{ route('users.create') }}" class="btn btn-secondary">Create New User</a>
                      </div>
                  </div>
              </div>
                <div class="col-md-9">
                    <div class="card">
                        <div class="card-header">Create New User</div>

                        <div class="card-body">
                            @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            @endif

                            <form method="POST" action="{{ route('users.store') }}">
                                @csrf

                                <div class="form-group row">
                                    <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('EIN') }}</label>

                                    <div class="col-md-6">
                                        <input id="ein" type="text" class="form-control{{ $errors->has('ein') ? ' is-invalid' : '' }}" name="ein" value="{{ old('ein') }}" required autofocus @blur="onBlur">

                                        @if ($errors->has('ein'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('ein') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <hr />

                                <div class="form-group row">
                                    <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('First Name') }}</label>

                                    <div class="col-md-6">
                                        <input id="first_name" type="text" class="form-control{{ $errors->has('first_name') ? ' is-invalid' : '' }}" name="name" :value="firstName" disabled>

                                        @if ($errors->has('first_name'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('first_name') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Middle Initial') }}</label>

                                    <div class="col-md-6">
                                        <input id="name" type="text" class="form-control{{ $errors->has('middle_initial') ? ' is-invalid' : '' }}" name="middle_initial" :value="middleInitial" disabled>

                                        @if ($errors->has('last_name'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('last_name') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>


                                <div class="form-group row">
                                    <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Last Name') }}</label>

                                    <div class="col-md-6">
                                        <input id="name" type="text" class="form-control{{ $errors->has('last_name') ? ' is-invalid' : '' }}" name="last_name" :value="lastName" disabled>

                                        @if ($errors->has('last_name'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('last_name') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Finance Number') }}</label>

                                    <div class="col-md-6">
                                        <input id="finance_number" type="text" class="form-control{{ $errors->has('finance_number') ? ' is-invalid' : '' }}" name="finance_number" :value="financeNumber" disabled>

                                        @if ($errors->has('name'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('name') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('DCO Craft') }}</label>

                                    <div class="col-md-6">
                                        <input id="dco_craft" type="text" class="form-control{{ $errors->has('dco_craft') ? ' is-invalid' : '' }}" name="dco_craft" :value="dcoCraft" disabled>

                                        @if ($errors->has('name'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('name') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <hr />

                                <div class="form-group row">
                                    <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('Username') }}</label>

                                    <div class="col-md-6">
                                        <input id="username" type="username" class="form-control{{ $errors->has('username') ? ' is-invalid' : '' }}" name="username" value="{{ old('username') }}" required>

                                        @if ($errors->has('username'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('username') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                    <div class="col-md-6">
                                        <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required>

                                        @if ($errors->has('email'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('email') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <hr />

                                <div class="form-group row">
                                    <label for="type" class="col-md-4 col-form-label text-md-right">{{ __('Type') }}</label>

                                    <div class="col-md-6">
                                        <select class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="type" value="{{ old('type') }}">
                                          <option value="0" @if(old('type') === 0) selected @endif>Member</option>
                                          <option value="1" @if(old('type') === 1) selected @endif>Steward</option>
                                          <option value="2" @if(old('type') === 2) selected @endif>Director, Research and Education</option>
                                          <option value="3" @if(old('type') === 3) selected @endif>Director, Human Relations</option>
                                          <option value="4" @if(old('type') === 4) selected @endif>Director, Organization</option>
                                          <option value="5" @if(old('type') === 5) selected @endif>Sergeant at Arms</option>
                                          <option value="6" @if(old('type') === 6) selected @endif>Chief Steward</option>
                                          <option value="7" @if(old('type') === 7) selected @endif>Director, Clerk Craft</option>
                                          <option value="8" @if(old('type') === 8) selected @endif>Director, Maintenance Craft</option>
                                          <option value="9" @if(old('type') === 9) selected @endif>Recording Secretary</option>
                                          <option value="10" @if(old('type') === 10) selected @endif>Corresponding Secretary</option>
                                          <option value="11" @if(old('type') === 11) selected @endif>Trustee</option>
                                          <option value="12" @if(old('type') === 12) selected @endif>Treasurer</option>
                                          <option value="13" @if(old('type') === 13) selected @endif>Vice President</option>
                                          <option value="14" @if(old('type') === 14) selected @endif>President</option>
                                        </select>

                                        @if ($errors->has('type'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('type') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                @if(Auth::user()->type === 12)
                                    <div class="form-group row">
                                        <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Authorized Payee') }}</label>

                                        <div class="col-md-6">
                                            <input type="checkbox" name="authorized_payee">
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Authorized Signer') }}</label>

                                        <div class="col-md-6">
                                            <input type="checkbox" name="authorized_signer">
                                        </div>
                                    </div>
                                    @endif

                                <div class="form-group row mb-0">
                                    <div class="col-md-6 offset-md-4">
                                        <button type="submit" class="btn btn-primary">
                                            {{ __('Save') }}
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endsection


        @section('vue')
            <script type="text/javascript">
                new Vue({
                    el: "#app",

                    data: {
                      firstName: "",
                      middleInitial: "",
                      lastName: "",
                      financeNumber: "",
                      dcoCraft: ""
                    },

                    methods: {
                      onBlur: function(event) {
                        axios.get("/local/employees/find/" + event.target.value)
                          .then((response) => {
                              data = response.data;

                              this.firstName = data.first_name;
                              this.middleInitial = data.middle_initial;
                              this.lastName = data.last_name;
                              this.financeNumber = data.finance_number;
                              this.daCode = data.status;
                          });
                      }
                    }
                });
            </script>
        @endsection

resources/views/system/users/index.blade.php
@extends('layouts.app')
    @section('content')
        <div class="container">
            <div class="row justify-content-center">
              <div class="col-md-3">
                  <div class="card">
                      <div class="card-header">Essential Links</div>

                      <div class="card-body">
                          <a href="{{ route('users.create') }}" class="btn btn-secondary">Create New User</a>
                      </div>
                  </div>
              </div>
                <div class="col-md-9">
                    <div class="card">
                        <div class="card-header">View User List</div>

                        <div class="card-body">
                            @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            @endif

                            <div class="table-responsive">
                               <table class="table table-bordered">
                                  <tr>
                                    <th>First Name</th>
                                    <th>Last Name</th>
                                    <th>EIN</th>
                                    <th>Type</th>
                                    <th>Actions</th>
                                  </tr>

                                  @foreach($users as $user)
                                    <tr>
                                      <td>{{ $user->profile->first_name }}</td>
                                      <td>{{ $user->profile->last_name }}</td>
                                      <td>{{ $user->ein }}</td>
                                      <td>{{ $user->type_text }}</td>
                                      <td>
                                        <a href="{{ route('users.edit', $user) }}" class="btn btn-secondary">Edit</a>

                                        <a class="btn btn-danger" href="{{ route('users.destroy', $user) }}"
                                           onclick="event.preventDefault();
                                                         document.getElementById('delete-{{ $user->id }}').submit();">Delete</a>
                                        <form id="delete-{{ $user->id }}" action="{{ route('users.destroy', $user) }}" method="POST">
                                          @method('DELETE')
                                          @csrf
                                        </form>
                                      </td>
                                    </tr>
                                  @endforeach

                               </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endsection